version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aloneislands_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./logs:/var/www/html/logs
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  db:
    image: mysql:5.7
    container_name: aloneislands_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: aloneislands
      MYSQL_USER: game_user
      MYSQL_PASSWORD: game_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: